---
- name: "security_zone.interface"
  include_tasks: security_zone.interface.yml
  loop: "{{ zone.interfaces | default([]) }}"
  loop_control:
    loop_var: interface

- name: "security_zone.address_book"
  include_tasks: security_zone.address_book.yml
  loop: "{{ zone.address_books | default([]) }}"
  loop_control:
    loop_var: address_book
