- name: "security_policies.source_address: Ensure state of match"
  vars:
    junos_config: set security policies from-zone {{ policy.from }} to-zone {{ policy.to }} policy {{ policy.name }} then {{ action.name }} {{ action.type | default(omit) }}
  set_fact:
    security_policy: "{{ security_policy }} + [ '{{ junos_config }}' ]"
  loop: "{{ policy.actions | default([]) }}"
  loop_control:
    loop_var: action
