inventory_root: "{{ playbook_dir }}/inventory"
key_root: "{{ playbook_dir }}/keys"
cloud_instance: "lab1"
cloud_project:  "paloalto"
cloud_provider: "aws"
cloud_region: "us-east-1"
cloud_user: ec2-user
cloud_name: "{{ cloud_instance }}.{{ cloud_project }}"
cloud_key_name: "{{ opt_key_name | default(cloud_project) }}"
cloud_private_key_file: "{{ key_root }}/{{ cloud_key_name }}.key"
cloud_public_key_file: "{{ key_root }}/{{ cloud_key_name }}.key.pub"
cloud_inventory_file: "{{ inventory_root }}/{{ cloud_project }}/hosts.yml"
cloud_vars_file: "{{ inventory_root }}/{{ cloud_project }}/all-vars.yml"
cloud_password: "Ansibull{{ lookup('password', '/dev/null chars=digits length=4') }}"
cloud_cidr: '10.1.0.0/16'
interfaces_in_inventory: no
