fabric_topology:
    - left_node: spine01
      right_node: leaf01
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.1.1/32
      right_ip: 169.254.101.1/32
      left_asn: 65001
      right_asn: 65101

    - left_node: spine01
      right_node: leaf02
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.1.2/32
      right_ip: 169.254.102.1/32
      left_asn: 65001
      right_asn: 65102

    - left_node: spine01
      right_node: leaf03
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.1.3/32
      right_ip: 169.254.103.1/32
      left_asn: 65001
      right_asn: 65103

    - left_node: spine01
      right_node: leaf04
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.1.4/32
      right_ip: 169.254.104.1/32
      left_asn: 65001
      right_asn: 65104

    - left_node: spine02
      right_node: leaf01
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.2.1/32
      right_ip: 169.254.101.2/32
      left_asn: 65002
      right_asn: 65101

    - left_node: spine02
      right_node: leaf02
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.2.2/32
      right_ip: 169.254.102.2/32
      left_asn: 65002
      right_asn: 65102

    - left_node: spine02
      right_node: leaf03
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.2.3/32
      right_ip: 169.254.103.2/32
      left_asn: 65002
      right_asn: 65103

    - left_node: spine02
      right_node: leaf04
      left_role: spine
      right_role: leaf
      left_interface: ethernet1/1
      right_interface: ethernet1/1
      left_ip: 169.254.2.4/32
      right_ip: 169.254.104.2/32
      left_asn: 65002
      right_asn: 65104
