vlans:
  - { name: vni101150, vlan_id: 1150, vlan_state: active, admin_state: up, state: present }
  - { name: pod01, vlan_id: 100, vlan_state: active, admin_state: up, state: present }
  - { name: app01, vlan_id: 101, vlan_state: active, admin_state: up, state: present }
  - { name: app02, vlan_id: 102, vlan_state: active, admin_state: up, state: present }
  - { name: app03, vlan_id: 103, vlan_state: active, admin_state: up, state: present }
  - { name: app04, vlan_id: 104, vlan_state: active, admin_state: up, state: present }
  - { name: app05, vlan_id: 105, vlan_state: active, admin_state: up, state: present }
