- name: "Ensure the state of vlans"
  net_vlan:
    aggregate: "{{ vlans }}"
    provider: "{{ provider }}"

- name: "Ensure strict state of vlans in trunk interfaces"
  nxos_l2_interface:
    aggregate: "{{ trunks }}"
    provider: "{{ provider }}"

- name: "Ensure state of vlan in access interfaces"
  nxos_l2_interface:
    aggregate: "{{ accesses }}"
    provider: "{{ provider }}"
