- name: "Network Configuration Snapshot"
  hosts: all
  gather_facts: yes
  connection: network_cli

  tasks:
    - name: "ansible-network.config_store"
      include_role:
        name: ansible-network.config_store
        tasks_from: config
      vars:
        config_store_version: "{{ hostvars[ansible_play_hosts[0]].ansible_date_time.iso8601_basic }}"
