- name: "OSPF Configuration"
  hosts: all
  connection: network_cli
  gather_facts: False

  vars:
    instance: 110

    areas:
      - { area: 1, type: nssa, network: 10.0.0.0, wildcard: 0.0.0.255 }
      - { area: 1, type: nssa, network: 192.168.0.0, wildcard: 0.0.0.255 }
      - { area: 2, type: nssa, network: 172.16.0.0, wildcard: 0.0.0.255 }

    redistributes:
      - { redistribute: static, metric: 210, route_map: STATIC->OSPF }
      - { redistribute: connected, metric: 200, route_map: CONNECTED->OSPF }

    route_maps:
      - { route_map: STATIC->OSPF, prefix_list: PERMIT_ALL }
      - { route_map: CONNECTED->OSPF, prefix_list: PERMIT_ALL }

    prefix_lists:
      - { prefix_list: PERMIT_ALL, action: permit, network: 0.0.0.0/0, le: 32 }

    interfaces:
      - { area: 1, interface: GigabitEthernet3, key: mykey, cost: 110 }
      - { area: 2, interface: GigabitEthernet4, key: mykey, cost: 110 }

  tasks:

    - name: "OSPF: Configure areas with networks"
      ios_config:
        parents: router ospf {{ instance }}
        lines:
          - area {{ ospf_area.area }} authentication message-digest
          - area {{ ospf_area.area }} {{ ospf_area.type }}
          - network {{ ospf_area.network }} {{ ospf_area.wildcard }} area {{ ospf_area.area }}
      with_items: "{{ areas }}"
      loop_control:
        loop_var: ospf_area
        label: "ospf_area {{ ospf_area.area }},{{ ospf_area.type }}"

    - name: "OSPF: Configure prefix-lists with networks"
      ios_config:
        lines:
          - ip prefix-list {{ ospf_prefix_list.prefix_list }} {{ ospf_prefix_list.action }} {{ ospf_prefix_list.network }} le {{ ospf_prefix_list.le }}
      with_items: "{{ prefix_lists }}"
      loop_control:
        loop_var: ospf_prefix_list
        label: "ospf_prefix_list {{ ospf_prefix_list.prefix_list }},{{ ospf_prefix_list.action }},{{ ospf_prefix_list.network }}"

    - name: "OSPF: Configure route-maps"
      ios_config:
        parents: route-map {{  ospf_route_map.route_map }} permit
        lines:
          - match ip address prefix-list {{ ospf_route_map.prefix_list }}
      with_items: "{{ route_maps }}"
      loop_control:
        loop_var: ospf_route_map
        label: "ospf_route_map {{ ospf_route_map.route_map }},{{ ospf_route_map.prefix_list }}"

    - name: "OSPF: Configure redistributes"
      ios_config:
        parents: router ospf {{ instance }}
        lines:
          - redistribute {{ ospf_redistribute.redistribute }} metric {{ ospf_redistribute.metric }} route-map {{ ospf_redistribute.route_map }}
      with_items: "{{ redistributes }}"
      loop_control:
        loop_var: ospf_redistribute
        label: "ospf_redistribute {{ ospf_redistribute.redistribute }},{{ ospf_redistribute.metric }}"

    - name: "OSPF: Configure interfaces"
      ios_config:
        parents: interface {{ ospf_interface.interface }}
        lines:
          - ip ospf authentication
          - ip ospf authentication-key {{ ospf_interface.key }}
          - ip ospf cost {{ ospf_interface.cost }}
          - ip ospf {{ instance }} area {{ ospf_interface.area }}
      with_items: "{{ interfaces }}"
      loop_control:
        loop_var: ospf_interface
        label: "ospf_interface {{ ospf_interface.interface }},{{ ospf_interface.area }},{{ ospf_interface.cost }}"
