- name: "Ensure state of Host Record"
  hosts: localhost
  gather_facts: no

  vars:
    nios_host_record_name: "ansible-test"
    nios_host_record_domain: "acme.com"
    nios_host_record_view: "Internal DNS"
    nios_host_record_subnet: "192.168.0.0/24"
    nios_host_record_ipv4addr: "{{ lookup('nios_next_ip', nios_host_record_subnet) }}"
    nios_host_record_state: "present"

  tasks:
    - name: "nios_next_ip data structure"
      debug:
        var: nios_host_record_ipv4addr
        verbosity: 2

    - name: "Ensure state of host record in NIOS"
      nios_host_record:
        name: "{{ nios_host_record_name }}.{{ nios_host_record_domain }}"
        view: "{{ nios_host_record_view | default(omit) }}"
        ipv4addrs:
          - ipv4addr: "{{ nios_host_record_ipv4addr[0] }}"
        state: "{{ nios_host_record_state }}"
      register: r_nios_host_record

    - name: "nios_host_record data structure"
      debug:
        var: r_nios_host_record
        verbosity: 2
