- name: "Ensure state of Host Record"
  hosts: localhost
  gather_facts: no

  vars:
    nios_provider:
      host: "{{ lookup('ENV', 'INFOBLOX_HOST') }}"
      username: "{{ lookup('ENV', 'INFOBLOX_USERNAME') }}"
      password: "{{ lookup('ENV', 'INFOBLOX_PASSWORD') }}"

    nios_host_record_host: "ansible-test"
    nios_host_record_domain: "acme.com"
    nios_host_record_fqdn: "{{ nios_host_record_host }}.{{ nios_host_record_domain }}"
    nios_host_record_exists: "{{ lookup('nios', 'record:host', filter={'name': nios_host_record_fqdn }) | default(omit, true) }}"
    nios_host_record_view: "Internal DNS"
    nios_host_record_subnet: "192.168.0.0/24"
    nios_host_record_ipv4addr: "{{ lookup('nios_next_ip', nios_host_record_subnet) }}"
    nios_host_record_state: "present"

  handlers:
    - name: "Ensure state of host record in NIOS"
    nios_host_record:
      provider: "{{ nios_provider }}"
      name: "{{ nios_host_record_fqdn }}"
      view: "{{ nios_host_record_view | default(omit) }}"
      ipv4addrs:
        - ipv4addr: "{{ nios_host_record_ipv4addr[0] }}"
      state: "{{ nios_host_record_state }}"
    listen: nios_host_record

  tasks:
    - debug:
        var: nios_host_record_exists

    - name: "Create only new host entries"
      debug:
        msg: "Calling handler to create new host entry in infoblox"
      changed_when: nios_host_record_exists is not defined