- name: "Ensure state of Host Record"
  hosts: localhost
  gather_facts: no

  vars:
    nios_host_record_name: "ansible-test"
    nios_host_record_view: "Internal DNS"
    nios_host_record_subnet: "10.36.200.0/24"
    nios_host_record_state: "present"

  tasks:
    - name: "Ensure state of host record in NIOS"
      nios_host_record:
        name: "{{ nios_host_record_name }}"
        view: "{{ nios_host_record_view | default(omit) }}"
        ipv4addrs:
          ipv4addr: "{{ lookup('nios_next_ip', nios_host_record_subnet) }}"
        state: "{{ nios_host_record_state }}"