- name: "POD01 Configuration"
  hosts: pod01
  connection: local
  gather_facts: no

  vars:
    features:
      - { name: lacp, state: enabled }
      - { name: vpc, state: enabled }

    vlans:
      - { name: pod01, vlan_id: 100, vlan_state: active, admin_state: up, state: present }
      - { name: app01, vlan_id: 101, vlan_state: active, admin_state: up, state: present }
      - { name: app02, vlan_id: 102, vlan_state: active, admin_state: up, state: present }
      - { name: app03, vlan_id: 103, vlan_state: active, admin_state: up, state: present }
      - { name: app04, vlan_id: 104, vlan_state: active, admin_state: up, state: present }

    portchannels:
      - { group: 12, members: ['ethernet1/2'], mode: active, admin_state: up, state: present }
      - { group: 13, members: ['ethernet1/3'], mode: active, admin_state: up, state: present }
      - { group: 14, members: ['ethernet1/4'], mode: active, admin_state: up, state: present }
      - { group: 15, members: ['ethernet1/5'], mode: active, admin_state: up, state: present }
      - { group: 16, members: ['ethernet1/6'], mode: active, admin_state: up, state: present }
      - { group: 17, members: ['ethernet1/7'], mode: active, admin_state: up, state: present }

    trunks:
      - { interface: port-channel12, native_vlan: 100, admin_state: up, state: present }
      - { interface: port-channel13, allowed_vlans: 100-104, native_vlan: 100, admin_state: up, state: present }
      - { interface: port-channel14, allowed_vlans: 100-104, native_vlan: 100, admin_state: up, state: present }
      - { interface: port-channel15, allowed_vlans: 100-104, native_vlan: 100, admin_state: up, state: present }
      - { interface: port-channel16, allowed_vlans: 100-104, native_vlan: 100, admin_state: up, state: present }
      - { interface: port-channel17, allowed_vlans: 100-104, native_vlan: 100, admin_state: up, state: present }

  tasks:
    - name: "Ensure state of features"
      nxos_feature:
        feature: "{{ feature.name }}"
        state: "{{ feature.state | default(omit) }}"
      with_items: "{{ features }}"
      loop_control:
        loop_var: feature
        label: "feature {{ feature.name }}"

    - name: "Ensure state of vlans"
      nxos_vlan:
        name: "{{ vlan.name }}"
        vlan_id: "{{ vlan.vlan_id }}"
        vlan_state: "{{ vlan.vlan_state | default(omit) }}"
        admin_state: "{{ vlan.admin_state | default(omit) }}"
        state: "{{ vlan.state | default(omit) }}"
      with_items: "{{ vlans }}"
      loop_control:
        loop_var: vlan
        label: "vlan {{ vlan.name }}, id {{ vlan.vlan_id }}"

    - name: "Ensure state of portchannels"
      nxos_portchannel:
        group: "{{ nxos_portchannel.group }}"
        members: "{{ nxos_portchannel.members }}"
        mode: "{{ nxos_portchannel.mode | default(omit) }}"
        state: "{{ nxos_portchannel.state | default(omit) }}"
      with_items: "{{ portchannels }}"
      loop_control:
        loop_var: nxos_portchannel
        label: "port-channel{{ nxos_portchannel.group }}"

    - name: "Ensure state of trunk interfaces as layer2"
      nxos_interface:
        interface: "{{ nxos_interface.interface }}"
        mode: layer2
        admin_state: "{{ nxos_interface.admin_state | default(omit) }}"
        state: "{{ nxos_interface.state | default(omit) }}"
      with_items: "{{ trunks }}"
      loop_control:
        loop_var: nxos_interface
        label: "interface {{ nxos_interface.interface }}"

    - name: "Ensure state of vpc on portchannels"
      nxos_vpc_interface:
        portchannel: "{{ nxos_vpc_interface.group }}"
        vpc: "{{ nxos_vpc_interface.group }}"
        peer_link: "{{ nxos_vpc_interface.peer_link }}"
        state: "{{ nxos_vpc_interface.state | default(omit) }}"
      when: "{{ nxos_vpc_interface.peer_link | default('false') }}"
      with_items: "{{ portchannels }}"
      loop_control:
        loop_var: nxos_vpc_interface
        label: "vpc {{ nxos_vpc_interface.group }}"

    - name: "Ensure state of vlans on trunks"
      nxos_switchport:
        interface: "interface {{ nxos_switchport.interface }}"
        mode: "trunk"
        native_vlan: "{{ nxos_switchport.native_vlan }}"
        trunk_allowed_vlans: "{{ nxos_switchport.allowed_vlans | default(nxos_switchport.native_vlan) }}"
        state: "{{ nxos_switchport.state | default(omit) }}"
      with_items: "{{ trunks }}"
      loop_control:
        loop_var: nxos_switchport
        label: "interface {{ nxos_switchport.interface }} allowed_vlans {{ nxos_switchport.allowed_vlans | default(nxos_switchport.native_vlan) }}"
