- name: "NXOS Command"
  hosts: all
  connection: network_cli

  vars:
    commands:
      - terminal length 0
      - show running-config arp
      - show ip arp vrf all
      - show ip arp static vrf all
      - show ip arp summary vrf all
      - show ip arp detail vrf all
      - show ip arp statistics vrf all

  tasks:
    - name: "show ip arp"
      nxos_command:
        commands: "{{ commands }}"
        timeout: 600
      register: show_ip_arp

    - debug: var=show_ip_arp.stdout_lines
