#### Always get version
- include_playbook: version.yml
####

- name: "NXOS Backup"
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: "Backup Configuration"
      nxos_config:
        backup: yes
