- name: "NXOS Backup"
  hosts: all
  connection: network_cli

  vars:
    backup_branch: "{{ lookup('pipe', 'date +%T') }}"
    backup_repo_user: "{{ lookup('ENV', 'SSH_USER' ) }}"
    backup_repo_private_key: "{{ lookup('ENV', 'SSH_PRIVATE_KEY') }}"
    backup_repo: ssh://git@github.com/{{backup_repo_user}}/config_store

  pre_tasks:
    - name: "Add private key to ssh-agent"
      block:
        - name: "Ensure state of ansible directory"
          file:
            path: "~/.ansible/tmp"
            state: directory

        - name: "Create file with the repository key"
          copy:
            content: "{{ backup_repo_private_key }}"
            path: "~/.ansible/tmp/git_ssh_private_key"

        - name: "Add key"
          shell: "ssh-add ~/.ansible/tmp/git_ssh_private_key"

      always:
        - name: "Ensure absence of key's file"
          file:
            path: "~/.ansible/tmp/git_ssh_private_key"
            state: absent

  tasks:
    - name: "create temporary directory to store configuration"
      changed_when: False
      tempfile:
        state: directory
        suffix: nxos_config
      register: r_tempfile

    - name: "clone the repository containing configurations"
      changed_when: False
      git:
        repo: "{{ backup_repo }}"
        dest: "{{ r_tempfile.path }}"
        clone: yes

    - name: "Ensure branch"
      block:
        - name: "Checkout branch"
          shell: git checkout -b {{ backup_branch }}
          args:
            chdir: "{{ r_tempfile.path }}"

        - name: "Push branch"
          shell: git push --force {{ backup_branch }}
          args:
            chdir: "{{ r_tempfile.path }}"

      always:
        - name: "Checkout branch"
          changed_when: False
          git:
            repo: "{{ backup_repo }}"
            dest: "{{ r_tempfile.path }}"
            version: "{{ backup_branch }}"
            clone: yes

    - name: "Fetch network configuration"
      nxos_config:
        backup: yes
      register: r_nxos_config

    - name: "Ensure folder structure"
      file:
        path: "{{ r_tempfile.path }}/{{inventory_hostname}}"
        state: directory

    - name: "Save network configuration"
      copy:
        src: "{{ r_nxos_config.backup_path }}"
        dest: "{{ r_tempfile.path }}/{{inventory_hostname}}/config.cfg"
        force: "yes"

    - name: "git add (untracked files)"
      changed_when: False
      shell: git add -A {{ backup_branch }}
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "git commit"
      block:
        - name: "Commit if there are any changes"
          shell: git commit -am "Network Backup"
          args:
            chdir: "{{ r_tempfile.path }}"
      rescue:
        - debug:
            msg: "Nothing to commit..."

    - name: "git push"
      changed_when: False
      shell: git push --force origin {{ branch|quote }}
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "Cleanup generated files/directories"
      changed_when: False
      file:
        path: "{{ cleanup }}"
        state: absent
      with_items:
        - "{{ r_nxos_config.backup_path | dirname }}"
        - "{{ r_tempfile.path }}"
      loop_control:
        loop_var: cleanup
        label: "cleanup {{ cleanup }}"
