- name: "NXOS Command"
  hosts: nxos
  connection: network_cli
  gather_facts: no

  vars:
#    check_arp_ip: 172.16.0.11
#    check_arp_mac: 5254.00b3.0117
    check_arp_vrf: all

  tasks:

    - name: "Check ipv4 entry in arp table"
      block:
        - name: "Validate entry"
          nxos_command:
            commands:
              - show ip arp vrf {{ check_arp_vrf }}
            wait_for:
              - result[0] contains check_arp_ip
          register: show_ip_arp_vrf_all
      rescue:
        - name: "Entry not found in device"
          debug:
            msg: "Entry not found in device"
      when: check_arp_ip is defined

    - name: "Check mac entry in arp table"
      block:
        - name: "Validate entry"
          nxos_command:
            commands:
              - show ip arp vrf {{ check_arp_vrf }}
            wait_for:
              - result[0] contains check_arp_mac
      rescue:
        - name: "Entry not found in device"
          debug:
            msg: "Entry not found in device"
      when: check_arp_mac is defined
