- name: "NXOS Command"
  hosts: all
  connection: local
  gather_facts: no

  vars:
    arps:
      - { host: 10.0.150.21, vrf: all }
      - { host: 10.0.150.22, vrf: all }

    macs:
      - { address: 0800.2737.a2d8, vni: 10150 }
      - { address: 0800.2756.c35f, vni: 10150 }
      - { address: 0800.27ce.8928, vni: 10150 }
      - { address: 0800.2701.5ca0, vni: 10150 }

  tasks:

    - name: "Get entries in mac address-table"
      nxos_command:
        commands:
          - show mac address-table address {{ mac.address }} vni {{ mac.vni }}
        wait_for:
         - result[0] contains mac.address
      with_items: "{{ macs }}"
      loop_control:
        loop_var: mac
        label: "{{ mac.address }}"

    - name: "Get entries in arp table"
      nxos_command:
        commands:
          - show ip arp {{ arp.host }} vrf {{ arp.vrf }}
        wait_for:
         - result[0] contains arp.host
      with_items: "{{ arps }}"
      when: arps is defined
      loop_control:
        loop_var: arp
        label: "{{ arp.host }}"
