- name: "NXOS Command"
  hosts: all
  connection: local
  gather_facts: no

  vars:
    arps:
      - { host: 10.42.0.1, vrf: all }
      - { host: 10.42.0.11, vrf: all }
      - { host: 10.42.0.12, vrf: all }
      - { host: 10.42.0.21, vrf: all }
      - { host: 10.42.0.22, vrf: all }
      - { host: 10.42.0.23, vrf: all }
      - { host: 10.42.0.24, vrf: all }
      - { host: 10.42.0.42, vrf: all }

    macs:
      - { address: 0800.2737.a2d8 }
      - { address: 0800.2756.c35f }
      - { address: 0800.27ce.8928 }
      - { address: 0800.2701.5ca0 }

  tasks:

    - name: "Get entries in mac address-table"
      nxos_command:
        commands:
          - show mac address-table address {{ mac.address }}
#        wait_for:
#         - result[0] contains mac.address
      with_items: "{{ macs }}"
      when: macs is defined
      loop_control:
        loop_var: mac
        label: "{{ mac.address }}"

    - name: "Get entries in arp table"
      nxos_command:
        commands:
          - show ip arp {{ arp.host }} vrf {{ arp.vrf }}
#        wait_for:
#         - result[0] contains arp.host
      with_items: "{{ arps }}"
      when: arps is defined
      loop_control:
        loop_var: arp
        label: "{{ arp.host }}"
