- name: "NXOS Command"
  hosts: nxos
  connection: network_cli
  gather_facts: no

  vars:
    ips:
      - 10.42.0.11
      - 10.42.0.12
      - 10.42.0.21
      - 10.42.0.22
      - 10.42.0.23
      - 10.42.0.24
      - 10.42.0.42

    macs:
      - 5254.00b3.0110
      - 5254.00b3.0120
      - 5254.00b3.0210
      - 5254.00b3.0220
      - 5254.00b3.0230
      - 5254.00b3.0240

  tasks:

    - name: "Get entries in mac address-table"
      nxos_command:
        commands:
          - show mac address-table
      register: show_mac_address_table

    - name: "Get entries in arp table"
      nxos_command:
        commands:
          - show ip arp vrf all
      register: show_ip_arp_vrf_all

    - name: "Check ip entry in show_ip_arp_vrf_all"
      block:
        - name: "Assert entry in show_ip_arp_vrf_all"
          assert:
            that:
              - "show_ip_arp_vrf_all.stdout_lines is match(ip)"
            fail_msg: "Fail: Entry not found for {{ ip }}"
            success_msg: "Success: Entry found for {{ ip }}"
          loop: "{{ ips }}"
          loop_control:
            loop_var: ip
            label: "ip: {{ ip }}"
      rescue:
        - name: "rescue"
          meta: clear_host_errors

    - name: "Check mac entry in show_mac_address_table"
      block:
        - name: "Assert entry in show_mac_address_table"
          assert:
            that: "show_mac_address_table.stdout_lines is match(mac)"
            fail_msg: "Fail: Entry not found for {{ mac }}"
            success_msg: "Success: Entry found for {{ mac }}"
          loop: "{{ macs }}"
          loop_control:
            loop_var: mac
            label: "mac: {{ mac }}"
      rescue:
        - name: "rescue"
          meta: clear_host_errors
