- name: "NXOS OSPF Command"
  hosts: all
  connection: network_cli

  vars:
    commands:
      - terminal length 0
      - show ip ospf vrf all
      - show ip ospf internal errors vrf all
      - show ip ospf neighbors detail vrf all
      - show ip ospf route vrf all
      - show ip ospf statistics vrf all

  tasks:
    - name: "show ip ospf"
      nxos_command:
        commands: "{{ commands }}"
      register: show_ospf

    - debug: var=show_ospf.stdout_lines
