---
- name: "Gather Junos: facts"
  hosts: junos
  connection: netconf
  gather_facts: no

  tasks:
    - name: Gather facts
      junos_facts:
      register: junos_facts

    - debug: var=junos_facts
