- name: "nxos_dhcp: Configure dynamic ip allocation requirements"
  nxos_config:
    save_when: modified
    lines:
      - ip dhcp relay
      - ip dhcp relay information option
      - ip dhcp relay information option vpn

## nxos_dhcp_interface
- name: "nxos_dhcp_interface: Ensure state of dhcp on underlay links"
  nxos_config:
    save_when: modified
    parents: interface {{ nxos_interface_underlay_amend_dhcp }}
    lines:
      - ip dhcp relay address {{ underlay_dhcp.address }} use-vrf {{ underlay_dhcp.vrf }}
      - ip address dhcp
  with_items: "{{ underlay_links }}"
  loop_control:
    loop_var: nxos_interface_underlay_amend_dhcp
    label: "nxos_interface_underlay_amend_dhcp {{ nxos_interface_underlay_amend_dhcp }}"
