- name: "Ensure the state of underlay features"
  nxos_feature:
    feature: "{{ nxos_feature.value.name }}"
    state: "{{ nxos_feature.value.states.state }}"
  with_dict: "{{ underlay_features }}"
  loop_control:
    loop_var: nxos_feature
    label: "nxos_feature {{ nxos_feature.key }}"

- name: "nxos_nv_overlay_epvn: Ensure state of evpn support"
  nxos_config:
    save_when: modified
    lines:
      - nv overlay evpn

## ethernet XX
- name: "Ensure state as layer3 on underlay links"
  nxos_interface:
    interface: "{{ nxos_interface_underlay_link }}"
    mode: layer3
    description: "{{ underlay_interfaces.link.description }}"
    admin_state: "{{ underlay_interfaces.link.states.admin }}"
    state: "{{ underlay_interfaces.link.states.state }}"
  with_items: "{{ underlay_links }}"
  loop_control:
    loop_var: nxos_interface_underlay_link
    label: "nxos_interface_underlay_link {{ nxos_interface_underlay_link }}"

## ethernet XX
## https://github.com/ansible/ansible/issues/33227
#- name: "Ensure state of vrf on underlay links"
#  nxos_vrf_interface:
#    interface: "{{ nxos_vrf_interface_underlay_link }}"
#    state: "{{ underlay_interfaces.link.states.state }}"
#    vrf: "{{ underlay_interfaces.link.vrf.name }}"
#  with_items: "{{ underlay_links }}"
#  loop_control:
#    loop_var: nxos_vrf_interface_underlay_link
#    label: "nxos_vrf_interface_underlay_link {{ nxos_vrf_interface_underlay_link }}"

##
- name: "Ensure state as Layer3 on control's and exchange's underlay interfaces"
  nxos_interface:
    interface: "{{ nxos_interface_l3_underlay.name }}"
    mode: layer3
    description: "{{ nxos_interface_l3_underlay.description }}"
    admin_state: "{{ nxos_interface_l3_underlay.states.admin }}"
    state: "{{ nxos_interface_l3_underlay.states.state }}"
  with_items:
    - "{{ underlay_interfaces.control }}"
    - "{{ underlay_interfaces.exchange }}"
  loop_control:
    loop_var: nxos_interface_l3_underlay
    label: "nxos_interface_l3_underlay {{ nxos_interface_l3_underlay.name }}"

## Ip of loopback0 and loopback1
- name: "Ensure state of Layer3 on control's and exchange's underlay interfaces"
  nxos_ip_interface:
    interface: "{{ nxos_ip_interface_l3_underlay.name }}"
    addr: "{{ nxos_ip_interface_l3_underlay.address }}"
    mask: 32
    state: "{{ nxos_ip_interface_l3_underlay.states.state }}"
  with_items:
    - "{{ underlay_interfaces.control }}"
    - "{{ underlay_interfaces.exchange }}"
  loop_control:
    loop_var: nxos_ip_interface_l3_underlay
    label: "nxos_ip_interface_l3_underlay {{ nxos_ip_interface_l3_underlay.name }}"

- name: "Import tasks for features"
  include_tasks: "{{ underlay_feature.value.name }}.yml"
  with_dict: "{{ underlay_features }}"
  loop_control:
    loop_var: underlay_feature
    label: "tasks from {{ underlay_feature }}"
