##  interface <underlay_links>
##    ip pim sparse-mode
- name: "Ensure state of exchange-plane on underlay links"
  nxos_pim_interface:
    interface: "{{ nxos_interface_pim }}"
    sparse: true
  with_items: "{{ underlay_links }}"
  loop_control:
    loop_var: nxos_interface_pim
    label: "nxos_interface_pim {{ nxos_interface_pim }}"

## ip pim rp-address <vars/main.yml:underlay_pim.rendezvous_point> group-list <vars/main.yml:underlay_pim.group_list>
- name: "Ensure state of exchange-plane rendezvous-point"
  nxos_pim_rp_address:
    rp_address: "{{ underlay_pim.rendezvous_point }}"
    group_list: "{{ underlay_pim.group_list }}"

# ip pim ssm range <vars/main.yml:underlay_pim.source_specific_multicast_range>
- name: "Ensure state of exchange-plane ssm-range"
  nxos_pim:
    ssm_range: "{{ underlay_pim.source_specific_multicast_range }}"

## ip pim rp-candidate <vars/main.yml:underlay_interfaces.exchange> group-list <vars/main.yml:underlay_pim.group_list>
- name: "nxos_pim_rp_candidate: SPINE: Configure exchange-plane candidature to become rendezvous-point"
  nxos_config:
    save_when: modified
    lines:
      - ip pim rp-candidate {{ underlay_interfaces.exchange.name }} group-list {{ underlay_pim.group_list }}
  when: inventory_hostname in groups['spine']

## ip pim anycast-rp <vars/main.yml:underlay_interfaces.exchange> <inventory/spine/<inventory_hostname>:control_plane_id>
- name: "nxos_pim_anycast_rp: SPINE: Configure anycasp-rp of exchange-plane"
  nxos_config:
    save_when: modified
    lines:
      - ip pim anycast-rp {{ underlay_pim.rendezvous_point }} {{ nxos_pim_anycast_rp }}
  when: inventory_hostname in groups['spine']
  with_items: "{{ groups['spine']|map('extract', hostvars, 'control_plane_id')|list }}"
  loop_control:
    loop_var: nxos_pim_anycast_rp
    label: "nxos_pim_anycast_rp {{ nxos_pim_anycast_rp }}"
