####### OSPF
##
- name: "Ensure state of ospf"
  nxos_ospf:
    ospf: "{{ underlay_ospf.name }}"
    state: "{{ underlay_ospf.states.state }}"

- name: "Ensure state of ospf on underlay links"
  nxos_interface_ospf:
    interface: "{{ nxos_interface_ospf_underlay_link }}"
    ospf: "{{ underlay_ospf.name }}"
    area: "{{ underlay_ospf.area }}"
    cost: "{{ underlay_ospf.cost }}"
    state: "{{ underlay_ospf.states.state }}"
    passive_interface: false
  with_items: "{{ underlay_links }}"
  loop_control:
    loop_var: nxos_interface_ospf_underlay_link
    label: "nxos_interface_ospf {{ nxos_interface_ospf_underlay_link }}"

## https://github.com/ansible/ansible/issues/33245
- name: "Ensure state of ospf on control and exchange loopback interfaces"
  nxos_interface_ospf:
    interface: "{{ nxos_interface_ospf_control_exchange.name }}"
    ospf: "{{ underlay_ospf.name }}"
    area: "{{ underlay_ospf.area }}"
    cost: "{{ underlay_ospf.cost }}"
    state: "{{ underlay_ospf.states.state }}"
#    passive_interface: true
  with_items:
    - "{{ underlay_interfaces.control }}"
    - "{{ underlay_interfaces.exchange }}"
  loop_control:
    loop_var: nxos_interface_ospf_control_exchange
    label: "nxos_interface_ospf {{ nxos_interface_ospf_control_exchange }}"
