- name: "Cloud Pod Configuration"
  hosts: all
  strategy: free
  connection: local
  gather_facts: no

  tasks:
    - name: "Ensure state of features"
      nxos_feature:
        feature: "{{ feature.name }}"
        state: "{{ feature.state | default(omit) }}"
      with_items: "{{ features }}"
      loop_control:
        loop_var: feature
        label: "feature {{ feature.name }}"

    - name: "Ensure state of vlans"
      nxos_vlan:
        name: "{{ vlan.name }}"
        vlan_id: "{{ vlan.vlan_id }}"
        vlan_state: "{{ vlan.vlan_state | default(omit) }}"
        admin_state: "{{ vlan.admin_state | default(omit) }}"
        state: "{{ vlan.state | default(omit) }}"
      with_items: "{{ vlans }}"
      loop_control:
        loop_var: vlan
        label: "vlan {{ vlan.vlan_id }},{{ vlan.name }}"

#    - name: "Ensure state of trunk interfaces as layer2"
#      nxos_interface:
#        interface: "{{ nxos_interface.interface }}"
#        mode: layer2
#        admin_state: "{{ nxos_interface.admin_state | default(omit) }}"
#        state: "{{ nxos_interface.state | default(omit) }}"
#      with_items: "{{ trunks }}"
#      loop_control:
#        loop_var: nxos_interface
#        label: "interface {{ nxos_interface.interface }}"

#    - name: "Ensure state of portchannels"
#      nxos_linkagg:
#        group: "{{ nxos_portchannel.group }}"
#        members: "{{ nxos_portchannel.members }}"
#        mode: "{{ nxos_portchannel.mode | default(omit) }}"
#        state: "{{ nxos_portchannel.state | default(omit) }}"
#        force: "{{ nxos_portchannel.force | default('true') }}"
#      with_items: "{{ portchannels }}"
#      loop_control:
#        loop_var: nxos_portchannel
#        label: "port-channel{{ nxos_portchannel.group }}"

    - name: "Ensure state of portchannels"
      nxos_config:
        lines:
          - interface port-channel{{ nxos_portchannel.group }}
      with_items: "{{ portchannels }}"
      loop_control:
        loop_var: nxos_portchannel
        label: "port-channel {{ nxos_portchannel.group }}"

    - name: "Ensure state of portchannel's members"
      nxos_config:
        parents: interface {{ nxos_portchannel_member.1 }}
        lines:
          - channel-group {{ nxos_portchannel_member.0.group }} mode {{ nxos_portchannel_member.0.mode }}
      with_subelements:
        - "{{ portchannels }}"
        - members
      loop_control:
        loop_var: nxos_portchannel_member
        label: "member {{ nxos_portchannel_member.1 }},{{ nxos_portchannel_member.0.group }}"

    - name: "Ensure state of vpc on portchannels"
      nxos_vpc_interface:
        portchannel: "{{ nxos_vpc_interface.group }}"
        vpc: "{{ nxos_vpc_interface.group }}"
        peer_link: "{{ nxos_vpc_interface.peer_link }}"
        state: "{{ nxos_vpc_interface.state | default(omit) }}"
      when: nxos_vpc_interface.peer_link is defined
      with_items: "{{ portchannels }}"
      loop_control:
        loop_var: nxos_vpc_interface
        label: "port-channel {{ nxos_vpc_interface.group }},{{ nxos_vpc_interface.group }}"

    - name: "Ensure state of vlans on trunks"
      nxos_switchport:
        interface: "{{ nxos_switchport.interface }}"
        mode: "trunk"
        native_vlan: "{{ nxos_switchport.native_vlan }}"
        trunk_allowed_vlans: "{{ nxos_switchport.allowed_vlans }}"
        state: "{{ nxos_switchport.state | default(omit) }}"
      with_items: "{{ trunks }}"
      loop_control:
        loop_var: nxos_switchport
        label: "trunk {{ nxos_switchport.interface }},{{ nxos_switchport.allowed_vlans }}"
