---
- name: "overlay: Configure ACL TCAM region for ARP suppression"
  nxos_config:
    defaults: true
    lines:
      - hardware access-list tcam region arp-ether 256 double-wide

- name: "overlay: Ensure state of Anycast GW"
  nxos_overlay_global:
    anycast_gateway_mac: "{{ overlay.anycast_gateway_mac }}"
