---
- name: "victorock.underlay-nxos-leaf-jinja2"
  block:
    - include_tasks: checkpoint.yml
    - include_tasks: build.yml
    - include_tasks: deploy.yml

  rescue:
    - include_tasks: rollback.yml
  when: inventory_hostname in groups['leaf']
