- name: "Portchannel Provisioning"
  hosts: all
  connection: local
  gather_facts: no

  vars:
    group: 10
    members: ['Ethernet1/1','Ethernet1/2']
    mode: active
    state: present

  tasks:
    - name: "Ensure portchannel {{ group }} is {{ mode }}"
      nxos_portchannel:
        group: "{{ group }}"
        members: "{{ members }}"
        mode: "{{ mode }}"
        state: "{{ state }}"
