- name: "VLAN Provisioning"
  hosts: all
  connection: local
  gather_facts: no

  vars:
    vlan_name: management
    vlan_id: 10
    vlan_state: active
    vlan_admin_state: up
    state: present

  tasks:
    - name: "Ensure vlan exists"
      nxos_vlan:
        name: "{{ vlan_name }}"
        vlan_id: "{{ vlan_id }}"
        vlan_state: "{{ vlan_state }}"
        admin_state: "{{ vlan_admin_state }}"
        state: "{{ state }}"
