interfaces:
  - name: mgmt
    ip: 10.1.0.254/24
    private_ip_address: 10.1.0.254
    private_ip_cidr: 10.1.0.254/24
  - name: ethernet1/1
    ip: 10.1.1.254/24
    private_ip_address: 10.1.1.254
    private_ip_cidr: 10.1.1.254/24
  - name: ethernet1/2
    ip: 10.1.2.254/24
    private_ip_address: 10.1.2.254
    private_ip_cidr: 10.1.2.254/24
    public_ip_address:
    public_dns_name:
