---
galaxy_info:
  author: victorock
  description: Underlay Network Configuration
  license: "license (BSD, MIT)"
  min_ansible_version: 2.5
  platforms:
    - name: NXOS
      versions:
        - 7
  galaxy_tags:
    - underlay
    - bgp
    - vxlan
    - evpn
    - multicast
    - nxos

dependencies:
  - victorock.underlay-nxos-spine
  - victorock.underlay-nxos-spine-jinja2
  - victorock.underlay-nxos-leaf
  - victorock.underlay-nxos-leaf-jinja2
