- name: "nxos_feature: Ensure the state of multicast feature"
  nxos_feature:
    feature: "{{ underlay_features.multicast.name }}"
    state: "{{ underlay_multicast.states.feature }}"
  tags:
    - multicast
    - underlay_leaf_multicast
    - underlay_nxos_leaf_multicast

- name: "nxos_pim_interface: Ensure state of multicast in control interfaces"
  nxos_pim_interface:
    interface: "{{ nxos_pim_interface.value.name }}"
    sparse: true
    state: "{{ underlay_multicast.states.state | default(underlay_states.state) }}"
  with_dict: "{{ nxos_pim_interface_control.control }}"
  loop_control:
    loop_var: nxos_pim_interface
    label: "nxos_pim_interface {{ nxos_pim_interface.value.name }}"
  tags:
    - multicast
    - underlay_leaf_multicast
    - underlay_nxos_leaf_multicast

- name: "nxos_pim_interface: Ensure state of multicast in links interfaces"
  nxos_pim_interface:
    interface: "{{ nxos_pim_interface_link.value.name }}"
    sparse: true
    state: "{{ nxos_pim_interface_link.state | default(underlay_states.state) }}"
  with_dict: "{{ underlay_interfaces.links }}"
  loop_control:
    loop_var: nxos_pim_interface_link
    label: "nxos_pim_interface {{ nxos_pim_interface_link.value.name }}"
  tags:
    - multicast
    - underlay_leaf_multicast
    - underlay_nxos_leaf_multicast

- name: "nxos_pim_rp_address: Ensure state of multicast rendezvous-point"
  nxos_pim_rp_address:
    rp_address: "{{ underlay_multicast.rendezvous_point }}"
    state: "{{ underlay_multicast.states.state }}"
  tags:
    - multicast
    - underlay_leaf_multicast
    - underlay_nxos_leaf_multicast
