- name: nxos_feature: Ensure the state of Overlay feature
  nxos_feature:
    feature: "{{ underlay_features.overlay.name }}"
    state: "{{ underlay_states.feature }}"
  tags:
    - underlay_leaf_overlay
    - underlay_nxos_leaf_overlay
