---
- name: "victorock.underlay-nxos-leaf"
  block:
    - include_tasks: checkpoint.yml
      tags:
        - checkpoint
        - lldp
        - l3_interface
        - bgp
        - overlay
        - vxlan
        - evpn
        - multicast

    - include_tasks: lldp.yml
      tags:
        - lldp
        - underlay_leaf_lldp
        - underlay_nxos_leaf_lldp

    - include_tasks: l3_interface.yml
      tags:
        - l3_interface
        - underlay_leaf_l3_interface
        - underlay_nxos_leaf_l3_interface

    - include_tasks: bgp.yml
      tags:
        - bgp
        - underlay_leaf_bgp
        - underlay_nxos_leaf_bgp

    - include_tasks: overlay.yml
      tags:
        - overlay
        - underlay_leaf_overlay
        - underlay_nxos_leaf_overlay

    - include_tasks: vxlan.yml
      tags:
        - vxlan
        - underlay_leaf_vxlan
        - underlay_nxos_leaf_vxlan

    - include_tasks: evpn.yml
      tags:
        - evpn
        - underlay_leaf_evpn
        - underlay_nxos_leaf_evpn

    - include_tasks: multicast.yml
      tags:
        - multicast
        - underlay_leaf_multicast
        - underlay_nxos_leaf_multicast

    - include_tasks: asserts.yml
      tags:
        - asserts
        - underlay_leaf_asserts
        - underlay_nxos_leaf_asserts

  rescue:
    - include_tasks: rollback.yml
      tags:
        - rollback
        - lldp
        - l3_interface
        - bgp
        - overlay
        - vxlan
        - evpn
        - multicast
