panos_nat_rules:
  - rule_name: 'NATAllOut'
    source_zone: ['trust']
    destination_zone: 'untrust'
    source_ip: ['any']
    destination_ip: ['any']
    snat_type: 'dynamic-ip-and-port'
    snat_interface: 'ethernet1/1'
