- name: "IOS Backup"
  hosts: ios
  connection: network_cli
  gather_facts: no

  vars:
    repo: ssh://git@github.com/victorock/network-configs
    branch: "snapshot"

  tasks:
    - name: "create temporary directory to store configuration"
      run_once: true
      changed_when: false
      tempfile:
        state: directory
        suffix: ios_config
      register: r_tempfile

    - name: "git clone"
      run_once: true
      changed_when: false
      git:
        accept_hostkey: true
        repo: "{{ repo }}"
        dest: "{{ r_tempfile.path }}"
        clone: yes

    - name: "git branch list"
      run_once: true
      changed_when: false
      register: git_branch_list
      shell: "git branch -a --list {{ branch }}"
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "git checkout new branch"
      when: git_branch_list.stdout_lines|length < 1
      run_once: true
      register: git_checkout
      shell: "git checkout -b {{ branch | quote }}"
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "git checkout existing branch"
      when: git_branch_list.stdout_lines|length > 0
      run_once: true
      register: git_checkout
      shell: "git checkout {{ branch | quote }}"
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "save and fetch network configuration"
      ios_config:
        save_when: "always"
        backup: yes
      register: r_ios_config

    - name: "remove non configuration lines"
      lineinfile:
        path: "{{ r_ios_config.backup_path }}"
        regexp: '^(Current|Building) configuration.*'
        state: absent

    - name: "create folder structure"
      changed_when: false
      file:
        path: "{{ r_tempfile.path }}/{{ inventory_hostname }}/config"
        state: directory

    - name: "copy network configuration to repo folder"
      copy:
        src: "{{ r_ios_config.backup_path }}"
        dest: "{{ r_tempfile.path }}/{{ inventory_hostname }}/config/running.cfg"
        force: "yes"

    - name: "Configure local git repository"
      shell: git config "{{ item.key }}" "{{ item.value }}"
      run_once: yes
      changed_when: false
      args:
        chdir: "{{ r_tempfile.path }}"
      loop:
        - { key: user.name, value: "Ansible Network" }
        - { key: user.email, value: "ansible-network@ansible.com" }
        - { key: branch.autosetupmerge, value: "always" }
        - { key: push.default, value: "current" }

    - name: "git add"
      shell: "git add {{ inventory_hostname }}/config/running.cfg"
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "git commit"
      run_once: true
      changed_when: git_commit.stdout.find("files changed") != -1
      register: git_commit
      shell: git commit -m "Network Backup"
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "git push"
      run_once: true
#      failed_when: git_push.stdout.find("error:") != -1
#      changed_when: git_push.stdout.find("remote:") != -1
      register: git_push
      shell: git push origin {{ branch|quote }}
      args:
        chdir: "{{ r_tempfile.path }}"

    - name: "Cleanup generated files/directories"
      changed_when: false
      run_once: true
      file:
        path: "{{ cleanup }}"
        state: absent
      with_items:
        - "{{ r_ios_config.backup_path | dirname }}"
        - "{{ r_tempfile.path }}"
      loop_control:
        loop_var: cleanup
        label: "cleanup {{ cleanup }}"
