- name: "IOS Command"
  hosts: ios
  connection: network_cli
  gather_facts: no

  vars:
    arp_ipv4: "192.168.35.101"
    arp_vrf: "GS"

  tasks:
    - name: "show ip arp {{ arp_ipv4 }} vrf {{ arp_vrf }}"
      ios_command:
        retries: 2
        interval: 1
        commands:
          - "show ip arp {{ arp_ipv4 }} vrf {{ arp_vrf | replace('\n', '') | replace('\r', '') }}"
        wait_for:
          - result[0] contains {{ arp_ipv4 }}