- name: "IOS Command"
  hosts: ios
  connection: network_cli
  gather_facts: no

  vars:
    commands:
      - terminal length 0
      - show ip ospf vrf all
      - show ip ospf internal errors vrf all
      - show ip ospf neighbors detail vrf all
      - show ip ospf route vrf all
      - show ip ospf statistics vrf all

  tasks:
    - name: "show ip ospf"
      ios_command:
        commands: "{{ commands }}"
