- name: "IOS Command"
  hosts: ios
  connection: network_cli
  gather_facts: no

  vars:
    commands:
      - show version

  tasks:
    - name: "show version"
      ios_command:
        commands: "{{ commands }}"
