interfaces:
  - name: ge-0/0/1
    units:
      - name: 101
        description: app01
        vlan: 101
        ipv4: 10.101.0.10/24

  - name: ge-0/0/1
    units:
      - name: 102
        description: app02
        vlan: 102
        ipv4: 10.102.0.10/24
