---
- name: "victorock.overlay-nxos-leaf"
  block:
    - name: "sanity.yml"
      include_tasks: sanity.yml

    - name: "checkpoint.yml"
      include_tasks: checkpoint.yml

    - name: "features.yml"
      include_tasks: features.yml
      vars:
        features: "{{ overlay_features }}"

    - name: "overlay.yml"
      include_tasks: overlay.yml
      vars:
        overlay: "{{ overlay_global }}"

    - name: "vtep.yml"
      include_tasks: vtep.yml
      vars:
        vtep: "{{ overlay_interfaces.vtep }}"

    - name: "vnis.yml"
      include_tasks: vnis.yml
      vars:
        vnis: "{{ overlay_vnis }}"

    - name: "asserts.yml"
      include_tasks: asserts.yml

  rescue:
    - name: "rollback.yml"
      include_tasks: rollback.yml

  when: inventory_hostname in groups['leaf']
