#######################
## OpenConfig         #
#######################
template:
  interface:
    access:
      description: "Automated by Ansible"
      type: ethernet
      mtu: 1500
      enabled: yes
      ethernet:
        auto-negotiate: yes
        duplex-mode: full
        enable-flow-control: yes
      switched-vlan:
        interface-mode: access
        access-vlan: 101

    trunk:
      description: "Automated by Ansible"
      type: ethernet
      mtu: 1500
      enabled: yes
      ethernet:
        auto-negotiate: yes
        duplex-mode: full
        enable-flow-control: yes
        aggregate-id: ae101
      switched-vlan:
        interface-mode: access
        native-vlan: 10
        access-vlan: 101
        trunk-vlans:
          - 100

    interlink:
      description: "Automated by Ansible"
      type: ethernet
      mtu: 1500
      enabled: yes
      ethernet:
        auto-negotiate: yes
        duplex-mode: full
        enable-flow-control: yes
        aggregate-id: ae0
      switched-vlan:
        interface-mode: trunk
        native-vlan: 10
        trunk-vlans:
          - 100

    uplink:
      description: "Automated by Ansible"
      type: ethernet
      mtu: 1500
      enabled: yes
      ethernet:
        auto-negotiate: yes
        duplex-mode: full
        enable-flow-control: yes
        aggregate-id: ae1
      switched-vlan:
        interface-mode: trunk
        native-vlan: 10
        trunk-vlans:
          - 100
