---
- name: "victorock.underlay-nxos-spine"
  block:
    - include_tasks: checkpoint.yml
      tags:
        - checkpoint
        - lldp
        - l3_interface
        - ospf
        - bgp
        - overlay
        - vxlan
        - evpn
        - multicast

    - include_tasks: lldp.yml
      tags:
        - lldp
        - underlay_spine_lldp
        - underlay_nxos_spine_lldp

    - include_tasks: l3_interface.yml
      tags:
        - l3_interface
        - underlay_spine_l3_interface
        - underlay_nxos_spine_l3_interface

    - include_tasks: ospf.yml
      tags:
        - ospf
        - underlay_spine_ospf
        - underlay_nxos_spine_ospf

    - include_tasks: bgp.yml
      tags:
        - bgp
        - underlay_spine_bgp
        - underlay_nxos_spine_bgp

    - include_tasks: overlay.yml
      tags:
        - overlay
        - underlay_spine_overlay
        - underlay_nxos_spine_overlay

    - include_tasks: vxlan.yml
      tags:
        - vxlan
        - underlay_spine_vxlan
        - underlay_nxos_spine_vxlan

    - include_tasks: evpn.yml
      tags:
        - evpn
        - underlay_spine_evpn
        - underlay_nxos_spine_evpn

    - include_tasks: multicast.yml
      tags:
        - multicast
        - underlay_spine_multicast
        - underlay_nxos_spine_multicast

    - include_tasks: asserts.yml
      tags:
        - asserts
        - underlay_spine_asserts
        - underlay_nxos_spine_asserts

  rescue:
    - include_tasks: rollback.yml
      tags:
        - rollback
        - lldp
        - l3_interface
        - ospf
        - bgp
        - overlay
        - vxlan
        - evpn
        - multicast
  when: inventory_hostname in groups['spine']
