- name: Add a NAT rule to the firewall
  hosts: panos
  connection: local
  gather_facts: False
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  vars:
    panos_object_serviceobject: "service-tcp-3389"
    panos_object_protocol: "tcp"
    panos_object_destination_port: "3389"
    panos_object_description: "RDP on port 3389"

    panos_nat_rule_name: 'RDP Inbound'
    panos_nat_source_zone: ['untrust']
    panos_nat_destination_zone: 'untrust'
    panos_nat_source_ip: ['any']
    panos_nat_destination_ip: ['10.1.1.254']
    panos_nat_service: 'service-tcp-3389'
    # or 'static-ip'
    panos_nat_snat_type: 'dynamic-ip-and-port'
    panos_nat_snat_interface: ['ethernet1/1']
    panos_snat_static_address: None
    panos_snat_bidirectional: None
    panos_nat_dnat_address: '10.1.2.11'
    panos_nat_dnat_port: '3389'

  tasks:
  - name: Add the necessary service object to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      serviceobject: "{{panos_object_serviceobject | default(omit)}}"
      protocol: "{{panos_object_protocol | default(omit)}}"
      destination_port: "{{panos_object_destination_port | default(omit)}}"
      description: "{{panos_object_description | default(omit)}}"
      operation: "add"

  - name: Create NAT rule on the firewall
    panos_nat_rule:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      rule_name: "{{panos_nat_rule_name | default(omit)}}"
      source_zone: "{{panos_nat_source_zone | default(omit)}}"
      destination_zone: "{{panos_nat_destination_zone | default(omit)}}"
      source_ip: "{{panos_nat_source_ip | default(omit)}}"
      destination_ip: "{{panos_nat_destination_ip | default(omit)}}"
      service: "{{panos_nat_service | default(omit)}}"
      snat_type: "{{panos_nat_snat_type| default(omit)}}"
      snat_interface: "{{panos_nat_snat_interface | default(omit)}}"
      snat_static_address: "{{panos_snat_static_address | default(omit)}}"
      snat_bidirectional: "{{panos_snat_bidirectional | default(omit)}}"
      dnat_address: "{{panos_nat_dnat_address| default(omit)}}"
      dnat_port: "{{panos_nat_dnat_port | default(omit)}}"
      operation: "add"
