- name: Add some objects to the firewall
  hosts: panos
  connection: local
  gather_facts: False
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Add an address object to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      addressobject: 'test-address'
      address: '192.168.100.89/24'
      address_type: 'ip-netmask'
      description: 'This is a test address object'
      operation: 'add'

  - name: Add another address object to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      addressobject: 'test-range'
      address: '192.168.100.100-192.168.100.200'
      address_type: 'ip-range'
      description: 'This is a another test address object'
      operation: 'add'

  - name: Add an address group to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      addressgroup: 'test-address-group'
      static_value: ['test-address','test-range']
      description: 'This is a test addressgroup'
      operation: 'add'

  - name: Add a service to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      serviceobject: 'service-xyz'
      protocol: 'tcp'
      destination_port: '8889'
      description: 'This is a test service object'
      operation: 'add'

  - name: Add another service to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      serviceobject: 'service-abc'
      protocol: 'tcp'
      destination_port: '5000,5001,6000-7000'
      description: 'This is a test service object'
      operation: 'add'

  - name: Add a service group to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      servicegroup: 'test-service-group'
      services: ['service-abc','service-xyz']
      description: 'This is a test servicegroup'
      operation: 'add'

  - name: Add a tag to the firewall
    panos_object:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      tag_name: 'Test'
      color: 'orange'
      description: 'This is test tag'
      operation: 'add'
