- name: Demonstrate how to use userif module to register / unregister userid
  hosts: panos
  connection: local
  gather_facts: False
  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: register username ivanb to 10.0.1.101
    panos_userid:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      operation: 'login'
      userid: 'ACMECORP\ivanb'
      register_ip: '10.0.1.101'

  - name: register username bob to 10.0.1.102
    panos_userid:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      operation: 'login'
      userid: 'ACMECORP\bob'
      register_ip: '10.0.1.102'

  - name: deregister username bob from 10.0.1.102
    panos_userid:
      ip_address: "{{ provider.host }}"
      username: "{{ provider.username }}"
      password: "{{ provider.password }}"
      operation: 'logout'
      userid: 'ACMECORP\bob'
      register_ip: '10.0.1.102'
