---
- name: "Configure the PAN NAT Rules"
  hosts: panos
  connection: local
  gather_facts: False

  vars:

    panos_nat_operation: 'add'
    panos_nat_rule_name: 'NATAllOut'
    panos_nat_source_zone: ['trust']
    panos_nat_destination_zone: 'untrust'
    panos_nat_source_ip: ['any']
    panos_nat_destination_ip: ['any']
    panos_nat_service: Null
    panos_nat_snat_type: 'dynamic-ip-and-port'
    panos_nat_snat_interface: 'ethernet1/1'
    panos_nat_dnat_address: Null
    panos_nat_dnat_port: Null
    panos_nat_commit: True

  tasks:
    - name: Create NAT rules
      panos_nat_rule:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        operation: "{{ panos_nat_operation | default(omit) }}"
        rule_name: "{{ panos_nat_rule_name }}"
        source_zone: "{{ panos_nat_source_zone }}"
        destination_zone: "{{ panos_nat_destination_zone }}"
        source_ip: "{{ panos_nat_source_ip }}"
        destination_ip: "{{ panos_nat_destination_ip | default(omit) }}"
        service: "{{ panos_nat_service | default(omit) }}"
        snat_type: "{{ panos_nat_snat_type | default(omit) }}"
        snat_interface: "{{ panos_nat_snat_interface | default(omit) }}"
        dnat_address: "{{ panos_nat_dnat_address | default(omit) }}"
        dnat_port: "{{ panos_nat_dnat_port | default(omit) }}"
        commit: "{{ panos_nat_commit | default(omit) }}"
      register: command_result
      failed_when: "'MODULE FAILURE' in command_result.msg"
      changed_when: "'successfully added' in command_result.msg"

    - name: "Ensure commit"
      panos_commit:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
