- name: Delete the test security rules from Panorama
  hosts: panos
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Delete test rule #1 from Panorama
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'delete'
      rule_name: 'Ansible test 1'
      devicegroup: 'shared_services_11022'

  - name: Delete test rule #2 from Panorama
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'delete'
      rule_name: 'Ansible test 2'
      devicegroup: 'shared_services_11022'

  - name: Delete test rule #3 from Panorama
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'delete'
      rule_name: 'Ansible test 3'
      devicegroup: 'shared_services_11022'
