---
- name: Configure the PAN system attributes
  hosts: eu-central-fr1:&cloud_pod01:&panos
  connection: local
  gather_facts: False
  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: check if ready
      changed_when: false
      panos_check:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        timeout: 600

    - name: "Ensure state of network interface"
      when: 
        - panos_interfaces is defined
        - panos_interfaces is iterable
      panos_interface:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        mode: "{{ panos_interface.mode | default(omit, true) }}"
        enable_dhcp: "{{ panos_interface.enable_dhcp | default(omit, true) }}"
        if_name: "{{ panos_interface.name }}"
        zone_name: "{{ panos_interface.zone | default('untrust') }}"
        create_default_route: "{{ panos_interface.default_route | default('no') }}"
        operation: "update"
        commit: False
      register: command_result
      failed_when: "'MODULE FAILURE' in command_result.msg"
      changed_when: "'already present' not in command_result.msg"
      loop: "{{ panos_interfaces | default([]) }}"
      loop_control:
        loop_var: panos_interface

    - name: "Ensure state of objects"
      when: 
        - panos_objects is defined
        - panos_objects is iterable
      panos_object:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        operation: "{{ panos_object.operation | default('add') }}"
        addressobject: "{{ panos_object.addressobject | default(omit) }}"
        address: "{{ panos_object.address | default(omit) }}"
        serviceobject: "{{ panos_object.serviceobject | default(omit) }}"
        destination_port: "{{ panos_object.destination_port | default(omit) }}"
        protocol: "{{ panos_object.protocol | default(omit) }}"
        description: "{{ panos_object.description | default(omit) }}"
      register: command_result
      failed_when: "'MODULE FAILURE' in command_result.msg"
      changed_when: "'already exists' not in command_result.msg"
      loop: "{{ panos_objects }}"
      loop_control:
        loop_var: panos_object

    - name: "Ensure state of NAT rules"
      when: 
        - panos_nat_rules is defined
        - panos_nat_rules is iterable
      panos_nat_rule:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        operation: "add"
        rule_name: "{{ panos_nat_rule.rule_name }}"
        source_zone: "{{ panos_nat_rule.source_zone }}"
        destination_zone: "{{ panos_nat_rule.destination_zone }}"
        source_ip: "{{ panos_nat_rule.source_ip | default (omit) }}"
        destination_ip: "{{ panos_nat_rule.destination_ip | default (omit) }}"
        service: "{{ panos_nat_rule.service | default(omit) }}"
        snat_type: "{{ panos_nat_rule.snat_type | default (omit) }}"
        snat_interface: "{{ panos_nat_rule.snat_interface | default (omit) }}"
        dnat_address: "{{ panos_nat_rule.dnat_address | default(omit) }}"
        dnat_port: "{{ panos_nat_rule.dnat_port | default(omit) }}"
        commit: "False"
      loop: "{{ panos_nat_rules }}"
      loop_control:
        loop_var: panos_nat_rule
      register: command_result
      failed_when: "'MODULE FAILURE' in command_result.msg"
      changed_when: "'successfully added' in command_result.msg"

    - name: "Ensure state of security rules"
      when: 
        - panos_security_rules is defined
        - panos_security_rules is iterable
      panos_security_rule:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
        operation: "{{ item.operation | default (omit) }}"
        rule_name: "{{ item.rule_name | default (omit) }}"
        service: "{{ item.service | default (omit) }}"
        description: "{{ item.description | default (omit) }}"
        source_zone: "{{ item.source_zone | default (omit) }}"
        destination_zone: "{{ item.destination_zone | default (omit) }}"
        action: "{{ item.action | default ('allow') }}"
        commit: False
      with_items: "{{ panos_security_rules | default([]) }}"
      register: command_result
      failed_when: "'MODULE FAILURE' in command_result.msg"
      changed_when: "'successfully added' in command_result.msg"

    - name: Commit the configure
      when: changed is defined
      panos_commit:
        ip_address: "{{ provider.host }}"
        username: "{{ provider.username }}"
        password: "{{ provider.password }}"
