---
- name: "Configure F5: time settings"
  hosts: tmos
  connection: local
  gather_facts: no

  vars:
    bigip_device_ntp_servers:
      - 169.254.169.123
    bigip_device_ntp_timezone: "America/New_York"

  tasks:
    - name: Ensure state of NTP settings
      bigip_device_ntp:
        server: "{{ ansible_host }}"
        user: "{{ network_username | default(omit) }}"
        password: "{{ network_password | default(omit) }}"
        validate_certs: no
        ntp_servers: "{{ bigip_device_ntp_servers }}"

    - name: Ensure state of timezone settings
      bigip_device_ntp:
        server: "{{ ansible_host }}"
        user: "{{ network_username | default(omit) }}"
        password: "{{ network_password | default(omit) }}"
        validate_certs: no
        timezone: "{{ bigip_device_ntp_timezone }}"
