
- name: "F5 Facts"
  hosts: tmos
  connection: local
  gather_facts: no

  vars:
    network_username: "root"
    network_password: "password"


  tasks:
    - name: Get BIG-IP facts
      bigip_facts:
        server: "{{ ansible_host }}"
        user: "{{ network_username }}"
        password: "{{ network_password }}"
        validate_certs: no
        include: "system_info,software,self_ip"
      register: bigip_facts

    - debug: var=bigip_facts
