---
- name: "Configure F5: hostname"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Ensure state of hostname
      bigip_hostname:
        server: "{{ ansible_host }}"
        user: "{{ network_username | default(omit) }}"
        password: "{{ network_password | default(omit) }}"
        hostname: "{{ inventory_hostname }}"
        validate_certs: "no"
