---
- name: "Collect F5: Facts"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Gather BIG-IP facts
      bigip_facts:
        server: "{{ ansible_host }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        validate_certs: "{{ provider.use_ssl }}"
        include: "system_info,software,self_ip"
      register: bigip_facts

    - debug: var=bigip_facts
