---
- name: "Collect F5: Facts"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Gather BIG-IP facts
      bigip_facts:
        server: "{{ provider.host }}"
        user: "{{ provider.username }}"
        password: "{{ provider.password }}"
        validate_certs: "{{ provider.use_ssl }}"
        include: "system_info,software,self_ip"
      register: bigip_facts

    - debug: var=bigip_facts
