---
- name: "Configure F5: hostname"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Ensure state of hostname
      bigip_hostname:
        server: "{{ ansible_host }}"
        user: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        hostname: "{{ inventory_hostname }}"
        validate_certs: "no"
