---
- name: "Configure F5: DNS setting"
  hosts: tmos
  connection: local
  gather_facts: no

  vars:
    bigip_device_dns_name_servers:
      - 8.8.8.8
      - 8.8.4.4
    bigip_device_dns_search:
      - localdomain
      - lab.local

  tasks:
    - name: Ensure state of DNS settings on the BIG-IP
      bigip_device_dns:
        server: "{{ provider.host }}"
        user: "{{ provider.username }}"
        password: "{{ provider.password }}"
        validate_certs: "{{ provider.use_ssl }}"
        hostname: "{{ inventory_hostname }}"
        name_servers: "{{ bigip_device_dns_name_servers }}"
        search: "{{ bigip_device_dns_search }}"
