---
- name: "Collect F5: Facts"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Gather BIG-IP facts
      bigip_facts:
        server: "{{ provider.server | default(omit) }}"
        server_port: "{{ provider.server_port | default(omit) }}"
        user: "{{ provider.user | default(omit) }}"
        password: "{{ provider.password | default(omit) }}"
        validate_certs: "{{ provider.validate_certs | default(omit) }}"
        include: "address_class,certificate,client_ssl_profile,device,device_group,interface,key,node,pool,provision,rule,self_ip,software,system_info,traffic_group,trunk,virtual_address,virtual_server,vlan"
      register: bigip_facts

    - debug: var=bigip_facts
