---
- name: "Collect F5: Facts"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  tasks:
    - name: Gather BIG-IP facts
      bigip_device_facts:
        server: "{{ inventory_hostname }}"
        gather_subset:
          - all
      register: bigip_device_facts

    - name: Debug bigip_device_facts
      debug:
        var: bigip_device_facts
        verbosity: 2
