---
- name: "Collect F5: Facts"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Gather BIG-IP facts
      bigip_facts:
        provider: "{{ provider | default(omit) }}"
        include: "system_info,software,self_ip"
      register: bigip_facts

    - debug: var=bigip_facts
