---
- name: "Configure F5: hostname"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Ensure state of hostname
      bigip_hostname:
        server: "{{ provider.host }}"
        user: "{{ provider.username }}"
        password: "{{ provider.password }}"
        validate_certs: "{{ provider.use_ssl }}"
        hostname: "{{ inventory_hostname }}"
