---
- name: "Configure F5: hostname"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  tasks:
    - name: Ensure state of hostname
      bigip_hostname:
        server: "{{ ansible_host | default(omit) }}"
        server_port: "{{ ansible_httpapi_port | default(omit) }}"
        hostname: "{{ inventory_hostname }}"
