---
- name: Configure the F5s hosts
  hosts: hosts
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure state of httpd
      yum:
        name: httpd
        state: present

    - name: Ensure state of service
      service:
        name: httpd
        state: started
