---
- name: "Configure F5: hostname"
  hosts: tmos
  connection: local
  gather_facts: no

  tasks:
    - name: Ensure state of hostname
      bigip_hostname:
        provider: "{{ provider | default(omit) }}"
        hostname: "{{ inventory_hostname }}"
