---
- name: "Configure F5: VLANs and interfaces"
  hosts: tmos
  connection: local
  gather_facts: no

  vars:
    bigip_vlans:
      - { name: app01, vlan_id: 101, untagged_interfaces: [ '1.1' ] }
      - { name: app02, vlan_id: 102, untagged_interfaces: [ '1.2' ] }

  tasks:
    - name: Ensure state of VLAN interfaces
      bigip_vlan:
        server: "{{ provider.host }}"
        user: "{{ provider.username }}"
        password: "{{ provider.password }}"
        validate_certs: "{{ provider.use_ssl }}"
        name: "{{ bigip_vlan.name }}"
        untagged_interfaces: "{{ bigip_vlan.untagged_interfaces | default(omit) }}"
        tagged_interfaces: "{{ bigip_vlan.untagged_interfaces | default(omit) }}"
      with_items: "{{ bigip_vlans | default([]) }}"
      loop_control:
        loop_var: bigip_vlan
