---
- name: "Configure F5: VLANs and interfaces"
  hosts: tmos:&{{ bigip_server }}
  connection: local
  gather_facts: no
  tasks:
    - name: Ensure state of VLAN interfaces
      bigip_vlan:
        server: "{{ ansible_ssh_host | default(omit) }}"
        name: "{{ bigip_vlan_name }}"
        untagged_interfaces: "{{ bigip_vlan_untagged_interfaces | default(omit) }}"
        tagged_interfaces: "{{ bigip_vlan_tagged_interfaces | default(omit) }}"