---
- name: "Configure F5: vservers and members"
  hosts: tmos
  connection: local
  gather_facts: no

  vars:

    bigip_vserver_pool_name: http-pool
    bigip_vserver_pool_partition: Common

    bigip_vserver_node_host: 10.1.2.10
    bigip_vserver_node_port: 80

    bigip_vserver_name: "{{ pool_name }}"
    bigip_vserver_destination: 10.1.1.252
    bigip_vserver_port: 80

  tasks:
    - name: Ensure state of pool settings
      bigip_pool:
        server: "{{ provider.server | default(omit) }}"
        server_port: "{{ provider.server_port | default(omit) }}"
        user: "{{ provider.user | default(omit) }}"
        password: "{{ provider.password | default(omit) }}"
        validate_certs: "{{ provider.validate_certs | default(omit) }}"
        name: "{{ bigip_vserver_pool_name }}"

    - name: Ensure state of node and pool membership
      bigip_pool_member:
        server: "{{ provider.server | default(omit) }}"
        server_port: "{{ provider.server_port | default(omit) }}"
        user: "{{ provider.user | default(omit) }}"
        password: "{{ provider.password | default(omit) }}"
        validate_certs: "{{ provider.validate_certs | default(omit) }}"
        pool: "{{ bigip_vserver_pool_name }}"
        host: "{{ bigip_vserver_node_host }}"
        port: "{{ bigip_vserver_node_port }}"

    - name: Ensure state of VirtualServer
      bigip_virtual_server:
        server: "{{ provider.server | default(omit) }}"
        server_port: "{{ provider.server_port | default(omit) }}"
        user: "{{ provider.user | default(omit) }}"
        password: "{{ provider.password | default(omit) }}"
        validate_certs: "{{ provider.validate_certs | default(omit) }}"
        name: "{{ bigip_vserver_name }}"
        destination: "{{ bigip_vserver_destination }}"
        port: "{{ bigip_vserver_port }}"
        pool: "{{ bigip_vserver_pool_name }}"
        snat: Automap
        validate_certs: False
