underlay_states:
  admin: up
  state: present
  shutdown: false

underlay_features:
  dhcp:
    name: dhcp
    states:
      state: enabled
  bgp:
    name: bgp
    states:
      state: enabled
  multicast:
    name: pim
    states:
      state: enabled
  ospf:
    name: ospf
    states:
      state: enabled
  lldp:
    name: lldp
    states:
      state: enabled

underlay_vrfs:
  control:
    description: "{{ description }}"
    name: control
    states: "{{ underlay_states }}"
  management:
    description: "{{ description }}"
    name: management
    states: "{{ underlay_states }}"
  exchange:
    description: "{{ description }}"
    name: control
    states: "{{ underlay_states }}"

underlay_interfaces:
  control:
    description: "{{ description }}"
    name: loopback0
    address: "{{ control_plane_id }}"
    states: "{{ underlay_states }}"
    vrf: "{{ underlay_vrfs.control }}"
  management:
    description: "{{ description }}"
    name: ethernet 1/1
    address: "{{ management_plane_id }}"
    states: "{{ underlay_states }}"
    vrf: "{{ underlay_vrfs.management }}"
  exchange:
    description: "{{ description }}"
    name: loopback1
    address: "{{ exchange_plane_id }}"
    states: "{{ underlay_states }}"
    vrf: "{{ underlay_vrfs.exchange }}"
  link:
    description: "{{ description }}"
    name: ethernet 1/2
    address: "{{ underlay_dhcp }}"
    states: "{{ underlay_states }}"
    vrf: "{{ underlay_vrfs.control }}"

underlay_controller:
  address: "{{ controller_id }}"
  vrf: "{{ underlay_vrfs.management }}"

underlay_dhcp:
  description: "{{ description }}"
  vrf: "{{ underlay_vrfs.management }}"
  address: "{{ underlay_controller.address }}"
  states: "{{ underlay_states }}"

underlay_ospf:
  description: "{{ description }}"
  router_id: "{{ underlay_interfaces.control.address }}"
  vrf: "{{ underlay_vrfs.control }}"
  name: UNDERLAY_0
  area: 0
  cost: 110
  states: "{{ underlay_states }}"

underlay_bgp:
  description: "{{ description }}"
  router_id: "{{ underlay_interfaces.control.address }}"
  vrf: "{{ underlay_vrfs.control }}"
  asn: 65001
  graceful_restart: true
  states: "{{ underlay_states }}"

underlay_pim:
  description: "{{ description }}"
  vrf: "{{ underlay_vrfs.control }}"
  source_specific_multicast_range: "232.0.0.0/8"
  group_ranges:  "225.0.0.0/8"
  rendezvous_point: "172.16.1.201"
  states: "{{ underlay_states }}"
