underlay_role: spine

underlay_interfaces:
  control:
    description: "{{ underlay_description }}"
    name: loopback0
    address: "{{ underlay_control_plane_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  exchange:
    description: "{{ underlay_description }}"
    name: loopback1
    address: "{{ underlay_exchange_plane_controller_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  links:
    ethernet1/2:
      name: ethernet1/2
      lldp_neighbor:
        leaf01:
          name: leaf01

    ethernet1/2:
      name: ethernet1/2
      lldp_neighbor:
        leaf02:
          name: leaf02

    ethernet1/2:
      name: ethernet1/2
      lldp_neighbor:
        leaf03:
          name: leaf03

    ethernet1/2:
      name: ethernet1/2
      lldp_neighbor:
        leaf04:
          name: leaf04
