underlay_role: spine

underlay_interfaces:
  control:
    description: "{{ underlay_description }}"
    name: loopback0
    address: "{{ underlay_device_control_plane_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  exchange:
    description: "{{ underlay_description }}"
    name: loopback1
    address: "{{ underlay_fabric_exchange_plane_controller_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  links:
    Ethernet1/2:
      name: ethernet1/2
      lldp_neighbor:
        leaf01:
          name: leaf01

    Ethernet1/3:
      name: Ethernet1/3
      lldp_neighbor:
        leaf02:
          name: leaf02

    Ethernet1/4:
      name: Ethernet1/4
      lldp_neighbor:
        leaf03:
          name: leaf03

    Ethernet1/5:
      name: Ethernet1/5
      lldp_neighbor:
        leaf04:
          name: leaf04

underlay_bgp:
  description: "{{ underlay_description }}"
  router_id: "{{ underlay_device_control_plane_address | ipaddr('address') }}"
  update_source: "{{ underlay_interfaces.control.name }}"
  asn: 65001
  graceful_restart: true
  states: "{{ underlay_states }}"

underlay_multicast:
  description: "{{ underlay_description }}"
  router_id: "{{ underlay_device_control_plane_address | ipaddr('address') }}"
  source_specific_multicast_range: "232.0.0.0/8"
  group_list:  "225.0.0.0/8"
  rendezvous_point: "{{ underlay_fabric_exchange_plane_controller_address | ipaddr('address') }}"
  states: "{{ underlay_states }}"
