overlay_global:
  anycast_gateway_mac: 0000.1111.2222

overlay_states:
  admin: up
  state: present
  shutdown: false
  feature: enabled

overlay_vnis:
  l2_150_10150:
    name: l2_150_10150
    vrf: tenant01
    vlan: 150
    vni: 10150
    svi: 10.1.150.1/24
    multicast:
      group: default
    route:
      distinguisher: auto
      target_both: auto
    states: "{{ overlay_states }}"
