underlay_role: leaf

underlay_interfaces:
  control:
    description: "{{ underlay_description }}"
    name: loopback0
    address: "{{ underlay_control_plane_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  links:
    ethernet1/2:
      name: ethernet1/2
      lldp_neighbor:
        spine01:
          name: spine01

    ethernet1/3:
      name: ethernet1/3
      lldp_neighbor:
        spine02:
          name: spine02
