underlay_role: leaf

underlay_interfaces:
  control:
    description: "{{ underlay_description }}"
    name: loopback0
    address: "{{ underlay_device_control_plane_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  links:
    Ethernet1/2:
      name: Ethernet1/2
      lldp_neighbor:
        spine01:
          name: spine01

    Ethernet1/3:
      name: Ethernet1/3
      lldp_neighbor:
        spine02:
          name: spine02

underlay_bgp:
  description: "{{ underlay_description }}"
  router_id: "{{ underlay_device_control_plane_address | ipaddr('address') }}"
  asn: 65001
  graceful_restart: true
  states: "{{ underlay_states }}"

underlay_multicast:
  description: "{{ underlay_description }}"
  router_id: "{{ underlay_device_control_plane_address | ipaddr('address') }}"
  source_specific_multicast_range: "232.0.0.0/8"
  group_list:  "225.0.0.0/8"
  rendezvous_point: "{{ underlay_fabric_exchange_plane_controller_address | ipaddr('address') }}"
  states: "{{ underlay_states }}"
