- name: "ACL Configuration"
  hosts: all
  connection: network_cli

  vars:
    acls:
      permit:
        - seq: 10
          name: SSH
          proto: tcp
          src: any
          dest: any
          dest_port: 22
          description: INC#XXXX, CR#YYYYY
          state: present

  tasks:
    - name: "Configure ACL permit rules"
      nxos_acl:
        action: "permit"
        name: "{{ acl.name }}"
        seq: "{{ acl.seq }}"
        proto: "{{ acl.proto }}"
        src: "{{ acl.src }}"
        src_port1: "{{ acl.src_port | default(omit) }}"
        src_port_op: "{{ acl.src_port_op | default(omit) }}"
        dest: "{{ acl.dest }}"
        dest_port1: "{{ acl.dest_port | default('any') }}"
        dest_port_op: "{{ acl.dest_port_op | default('eq') }}"
        state: "{{ acl.state | default(omit) }}"
      loop: "{{ acls.permit }}"
      loop_control:
        loop_var: acl
