- name: "banner configuration"
  hosts: all
  connection: local
  gather_facts: no

  vars:
    banner: motd
    text: |
      this is my exec banner
      that contains a multiline
      string
    state: present

  tasks:
    - name: "Set banner always to motd as exec is not supported in nxos"
      set_fact:
        banner: motd
      when: "'motd' not in banner"

    - name: "Ensure banner message state"
      nxos_banner:
        banner: "{{ banner }}"
        text: "{{ text }}"
        state: "{{ state }}"
