- name: "NXOS Command"
  hosts: all
  connection: network_cli

  vars:
    commands:
      - show version

  tasks:
    - name: "Ad-Hoc commands"
      nxos_command:
        commands: "{{ commands }}"
