- name: "Feature Provisioning"
  hosts: all
  connection: network_cli

  vars:
    feature: lacp
    state: present

  tasks:
    - name: "set feature_state to enabled when defined present"
      set_fact:
        feature_state: enabled
      when: state == 'present'

    - name: "set feature_state to disabled when defined absent"
      set_fact:
        feature_state: disabled
      when: state == 'absent'

    - name:"Ensure feature state"
      block:
        - name: "Ensure {{ feature }} is enabled"
          nxos_feature:
            feature: "{{ feature }}"
            state: "{{ feature_state }}"
      rescue:
        - name: "Ensure {{ feature }} is enabled"
          nxos_config:
            lines:
              - feature {{ feature }}
          when: feature_state == 'enabled'

        - name: "Ensure {{ feature }} is disabled"
          nxos_config:
            lines:
              - no feature {{ feature }}
          when: feature_state == 'disable'
