- name: "VRRP Configuration"
  hosts: all
  connection: network_cli

  vars:
    interface: vlan10
    group: 100
    vipr: 10.1.10.1
    preempt: false
    priority: 130
    authentication: my_key
    state: present

  tasks:
    - name: "Configure VRRP on interface"
      nxos_vrrp:
        interface: "{{ interface }}"
        group: "{{ group }}"
        vip: "{{ vip }}"
        preempt: "{{ preempt }}"
        priority: "{{ priority }}"
        authentication: "{{ authentication }}"
        state: "{{ state }}"
