- name: "VPC Configuration"
  hosts: all
  connection: network_cli

  vars:
    portchannel: 10
    vpc: 10
    peer_link: false
    state: present

  tasks:
  - name: "Configure VPC on portchannel"
    nxos_vpc_interface:
      portchannel: "{{ portchannel }}"
      vpc: "{{ vpc }}"
      peer_link: "{{ peer_link }}"
      state: "{{ state }}"
