- name: "Switchport Provisioning"
  hosts: all
  connection: network_cli

  vars:
    interface: ethernet1/1
    mode: trunk
    native_vlan: 15
    trunk_vlans: 10-20
    state: present

  tasks:
    - name: "Ensure switchport configuration"
      nxos_switchport:
        interface: "{{ interface }}"
        mode: "{{ mode }}"
        native_vlan: "{{ native_vlan }}"
        trunk_vlans: "{{ trunk_vlans }}"
