---
- name: "victorock.underlay-nxos-spine-jinja2"
  block:
    - include_tasks: checkpoint.yml
    - include_tasks: build.yml
    - include_tasks: deploy.yml

  rescue:
    - include_tasks: rollback.yml
