net_l3_interface_state: present
net_l3_interface_aggregate:
#####################################################
# Loopback Template
# - name: <lopback##>
#   ipv4: <ip/mask>
## Loopback 0
  - name: loopback0
    ipv4: 1.1.1.14/32

#####################################################
## Cisco Template
# - name: <ethernet##>
#   ipv4: <ip/mask>
###
## Cumulus Template
# - name: <swp##>
#   ipv4: <ip/mask>
###
## Juniper Template
# - name: <em##>
#   ipv4: <ip/mask>
###
####################################################
## em0
  - name: em0
    ipv4: "{{ l3_links.link7.2 }}/30"

## em1
  - name: em1
    ipv4: "{{ l3_links.link8.2 }}/30"

####################################################
# Cisco Template
# - name: <vlan##>
#   ipv4: <ip/mask>
###
# Juniper Template
# - name: <vlan.##>
#   ipv4: <ip/mask>
###
####################################################
## Vlan 30
  - name: vlan.31
    ipv4: 172.16.31.3/24
