---
- name: Ensure state of selfip address on interface
  bigip_selfip:
    server: "{{ provider.host }}"
    user: "{{ provider.username | default(omit) }}"
    password: "{{ provider.password | default(omit) }}"
    validate_certs: "{{ provider.use_ssl | default(omit) }}"
    name:  "{{ interface.name }}"
    address: "{{ interface.ipv4 | ipaddr('address') }}"
    netmask: "{{ interface.ipv4 | ipaddr('netmask') }}"
    vlan: "{{ interface.vlan | default(omit) }}"
    state: "{{ interface.state | default(omit) }}"
