---
underlay_description: "Underlay by Ansible"

underlay_rollback:
  configuration: "underlay_nxos_spine.cfg"

underlay_states:
  admin: up
  state: present
  shutdown: false
  feature: enabled

underlay_features:
  ospf:
    name: ospf
    states: "{{ underlay_states }}"
  bgp:
    name: bgp
    states: "{{ underlay_states }}"
  multicast:
    name: pim
    states: "{{ underlay_states }}"
  lldp:
    name: lldp
    states: "{{ underlay_states }}"
  overlay:
    name: nv overlay
    states: "{{ underlay_states }}"
  vxlan:
    name: vn-segment-vlan-based
    states: "{{ underlay_states }}"

underlay_interfaces:
  control:
    description: "{{ underlay_description }}"
    name: loopback0
    address: "{{ underlay_device_control_plane_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  exchange:
    description: "{{ underlay_description }}"
    name: loopback1
    address: "{{ underlay_fabric_exchange_plane_controller_address | ipaddr('host') }}"
    states: "{{ underlay_states }}"
  links:
    Ethernet1/2:
      name: Ethernet1/2
      lldp_neighbor:
        spine01:
          name: leaf01

underlay_ospf:
  description: "{{ underlay_description }}"
  name: UNDERLAY_0
  area: 0.0.0.1
  cost: 1

underlay_bgp:
  description: "{{ underlay_description }}"
  router_id: "{{ underlay_device_control_plane_address | ipaddr('address') }}"
  asn: 65001
  graceful_restart: true
  states: "{{ underlay_states }}"

underlay_multicast:
  description: "{{ underlay_description }}"
  router_id: "{{ underlay_device_control_plane_address | ipaddr('address') }}"
  source_specific_multicast_range: "232.0.0.0/8"
  group_list:  "225.0.0.0/8"
  rendezvous_point: "{{ underlay_fabric_exchange_plane_controller_address | ipaddr('address') }}"
  states: "{{ underlay_states }}"
