---
overlay_description: "Overlay by Ansible"

overlay_rollback:
  configuration: "overlay_nxos_leaf.cfg"

overlay_global:
  anycast_gateway_mac: 0000.1111.2222

overlay_states:
  admin: up
  state: present
  shutdown: false
  feature: enabled

overlay_features:
  svi:
    name: interface-vlan
    states: "{{ overlay_states }}"
  overlay:
    name: nv overlay
    states: "{{ overlay_states }}"
  vxlan:
    name: vn-segment-vlan-based
    states: "{{ overlay_states }}"

overlay_interfaces:
  control:
    name: loopback0
    description: "{{ overlay_description }}"
    states: "{{ overlay_states }}"
  vtep:
    name: nve1
    description: "{{ overlay_description }}"
    states: "{{ overlay_states }}"
  links:
    Ethernet1/4:
      name: Ethernet1/4
      mode: access
      lldp_neighbor:
        server01:
          name: server01

overlay_vnis:
  150_10150:
    name: 150_10150
    vrf: tenant01
    l2:
      vlan: 150
      vni: 10150
      svi: 10.0.150.1/24
    l3:
      vlan: 1150
      vni: 101150
      svi: 10.1.150.1/24
    multicast:
      group: default
    route:
      distinguisher: auto
      import: auto
      export: auto
    links:
      Ethernet1/4:
        name: Ethernet1/4
    states: "{{ overlay_states }}"
