panos_security_rules:
  - rule_name: 'Incoming SSH'
    service: 'service-ssh'
    description: 'Allow Incoming SSH traffic'
    destination_zone: 'trust'
    source_zone: ['untrust']
  - rule_name: 'Outgoing All'
    description: 'Allow All Outgoing traffic'
    destination_zone: 'untrust'
    source_zone: ['trust']
