- name: "IOS Config"
  hosts: all
  connection: local
  gather_facts: no

  vars:
    backup: yes
    save_when: always
    replace: block
    match: exact
    before: no ip access-list test
    lines:
      - 10 permit ip 1.1.1.1/32 any log
      - 20 permit ip 2.2.2.2/32 any log
      - 30 permit ip 3.3.3.3/32 any log
      - 40 permit ip 4.4.4.4/32 any log
      - 50 permit ip 5.5.5.5/32 any log
    parents: ip access-list test

  tasks:
    - name: "Ad-Hoc Configuration"
      ios_config:
        backup: "{{ backup }}"
        save_when: "{{ save_when }}"
        replace: "{{ replace }}"
        match: "{{ match }}"
        before: "{{ before }}"
        lines: "{{ lines }}"
        parents: "{{ parents }}"
