- name: "OSPF Configuration"
  hosts: ios
  connection: network_cli
  gather_facts: no

  vars:
    instance: 110
    area: 1
    type: nssa

  tasks:
    - name: "Configure OSPF area"
      ios_config:
        parents: router ospf {{ instance }}
        lines:
          - area {{ area }} authentication message-digest
          - area {{ area }} {{ type }}
